# Generated by Django 6.0.6 on 2026-06-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('category', models.CharField(default='unknown', max_length=50)),
                ('risk_level', models.CharField(default='LOW', max_length=20)),
                ('confidence', models.FloatField(default=0)),
                ('allowed', models.BooleanField(default=True)),
                ('decision', models.CharField(default='ALLOW', max_length=20)),
                ('report_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
