# Generated by Django 6.0.6 on 2026-06-10 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moderationresult',
            name='decision',
        ),
        migrations.AddField(
            model_name='moderationresult',
            name='identity_attack_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='moderationresult',
            name='insult_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='moderationresult',
            name='obscene_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='moderationresult',
            name='severe_toxicity_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='moderationresult',
            name='threat_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='moderationresult',
            name='toxicity_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='moderationresult',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='moderationresult',
            name='risk_level',
            field=models.CharField(max_length=20),
        ),
    ]
